### ISSUE TITLE
Graph preprocessing error

### ISSUE THREAD

**Issue by atsyplenkov** [mtangi/cascademodel#4]
Hi there,

I'm trying to run CASCADE on my Windows machine with a demo Vjosa river dataset. While the `extract_river_network` part went surprisingly well, I faced a strange error in first part of `CASCADE_model` after running the following code:

```
addpath(genpath(pwd))
load('Vjosa_ReachData');
Network = graph_preprocessing(ReachData);
```

Error:
```
Undefined function 'graphshortestpath' for input arguments of type
'double'.

Error in graph_preprocessing>@(fromnode)graphshortestpath(Dus,fromnode)
(line 35)
 (arrayfun(@(fromnode)
 graphshortestpath(Dus,fromnode),FromN,'UniformOutput',false));

Error in graph_preprocessing (line 35)
 (arrayfun(@(fromnode)
 graphshortestpath(Dus,fromnode),FromN,'UniformOutput',false));

Error in main_script_CASCADE (line 18)
Network = graph_preprocessing(ReachData);
```

I'm using Windows 10, Matlab R2021a, TopoToolbox 2.4

**Comment by aesgeorges** [comment]
I am currently facing the same issue with the graphshortestpath function being 'unrecognized.'  Did you find a workaround by any chance?

**Comment by mtangi** [comment]
The function graphshortestpath was removed by MATLAB in version 2022b. I've uploaded a new graph_preprocessing function which should solve the problem.
